title: The parent detector
hero_image: images/banner.png
description: Detect intruders with a Raspberry Pi
original_url: https://www.raspberrypi.org/learning/parent-detector
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: builder, design-0, programming-1, phys-comp-2, manufacture-0, community-0
interests: ""
technologies: "raspberry-pi, python, physical computing"
steps:
  - title: Introduction
  - title: What you will need
  - title: Connect the PIR sensor
  - title: Connect the camera
  - title: Test the PIR sensor
  - title: Set up the camera preview
  - title: Record video to a file
  - title: Play video
  - title: "Challenge: stealth mode"
